export const MESSAGES = {
    SUCCESS: {
      OTP_SENT: "OTP sent to email",
      OTP_RESENT: "OTP resent successfully",
      OTP_VERIFIED: "OTP verified successfully",
      LOGIN_SUCCESS: "Login successful",
      TOKEN_REFRESHED: "Access token refreshed successfully",
      LOGOUT_SUCCESS: "Logout successful",
      PASSWORD_RESET_SENT: "Password reset email sent",
      PASSWORD_RESET_SUCCESS: "Password reset successfully",
      PROFILE_UPDATED: "Profile updated successfully",
      CAR_UPLOADED: "Car uploaded successfully",
      CARS_FETCHED: "Cars fetched successfully",
      PROFILE_FETCHED: "Profile fetched successfully",
      ID_PROOF_UPDATED: "ID Proof updated successfully",
      STATUS_UPDATED: "Status updated successfully",    
      OWNERS_FETCHED: "Car owners fetched successfully",  
      CAR_UPDATED:"Car Detail Update d Successfully",
      CUSTOMERS_FETCHED: "Customers fetched successfully",
      COMPLETED_REGISTRATION_FORM:"Completed Registration Form"
    },
    ERROR: {
      MISSING_FIELDS: "Required fields are missing",
      EMAIL_REQUIRED: "Email is required",
      INVALID_CREDENTIALS: "Invalid email or password",
      UNAUTHORIZED: "Unauthorized access",
      CUSTOMER_NOT_FOUND: "Customer not found",
      FORBIDDEN: "Access forbidden",
      PROFILE_NOT_FOUND: "Owner profile not found",
      NO_OWNER_ID_FOUND: "Forbidden: No car owner ID found",
      NO_CUSTOMER_ID_FOUND: "Forbidden: No customer ID found",
      NO_UPDATE_DATA: "No data provided to update.",
      NOT_FOUND: "Resource not found",
      SERVER_ERROR: "Something went wrong. Please try again later",
      OTP_INVALID: "Invalid OTP",
      NO_REFRESH_TOKEN: "No refresh token found",
      INTERNAL_SERVER_ERROR: "Internal server error",
    ADMIN_NOT_FOUND: "Admin not found"
    },
  };
  